package com.cognizant.cloudone.ui.constants;

/****
 * A class that contains the type of entities that Data Grid can have. This
 * entity is one of the critical property of the data grid meta info object and
 * act as "decision maker" for the data processing and formatting.
 * 
 * Each use case requiring to build Data Grid need to set this attribute while
 * building the meta info for the data grid.
 * 
 */
public enum DataGridEntityEnum {

	UNKNOWN, INSTANCE, EVENT, DEPLOYMENT, PROVISIONING_WORKFLOW, INTELLIGENT_PLACEMENT, USER, INSTANCE_SERVICEPROFILE, 
	S3BUCKET, S3BUCKET_EXPIRATION_RULES, MONITORING_PROFILE, SECURITY_GROUPS, SECURITY_GROUPS_SAVVIS, SECURITY_GROUPS_AZURE, CONSUMPTIONMETERING, INSTANCE_GROUP, 
	ELASTIC_IP,ELASTIC_IP_AWS,ELASTIC_IP_AZURE, KEY_PAIR, DIAGNOSTICS, JOB_MANAGEMENT, SCHEDULED_TASK, AUDIT_LOG, EBSSNAPSHOT, RULES_SECURITY_GROUP, 
	USER_GROUP, IMPORT_USER, IMAGES_CREATE_NEW_INSTANCE, REPORTING,ALLREPORTS, USER_GROUP_ROLE, EBS_VOLUME, APPLY_EBS_VOLUME, DATASTORE, DATASTORE_VMWARE, DATASTORE_POWERVM, 
	DATASTORE_NETAPP, DISK_LUNS_DATASTORE, MONITORING_PROFILE_PARAMETER, DISK_STORAGE_POOL, NETWORK_INTERFACES, AZURE_DATASTORES, 
	AZURE_IMAGE_CREATE_INSTANCE, APPLY_AZURE_MONITORING_PROFILE, DATABASE_SERVICES_AWS,DATABASE_SERVICES_AZURE, APPLICATIONS,WEBAPPSAPPLICATIONS, APPLICATIONAVAILABILITY, CLOUD_SERVICES,
    LOAD_BALANCERS, LOAD_BALANCERS_SAVVIS, LOAD_BALANCER_INSTANCES,LOAD_BALANCER_SAVVIS_INSTANCES,LOAD_BALANCER_NETSCALER_INSTANCES,LOAD_BALANCER_NETSCALER,STORAGE_PROFILE,STORAGE_PROFILE_CONFIGURATION,NETAPPSTORAGECATALOG,RECLAMATION,SNAPSHOT,DATABASESNAPSHOTS,
    CLUSTERDATASTORE, BILLING, DATASTORE_OPENSTACK, OPENSTACKSTORAGESNAPSHOT,PATCH,MANAGE_ENDPOINT,PAAS_DETAILS,MANAGE_ACL,DATASTORE_AZURE,AZURE_SELECT_STORAGE, AZURE_OBJECT_STORAGE, AZURE_STORAGE_CONTAINER, AZURE_STORAGE_BLOBS,APPLICATION_PROFILE,
    CHANGE_TRACKING,NETWORK_INTERFACES_AZURE,PATCH_INSTANCE,CONSUMPTIONMETERINGAMAZON,PHYSICAL_INSTANCE,DOWNLOADREPORTS,PENDING_REQUESTS,IMAGES,ADD_IMAGE;

}
